OMS/urls.py
from django.conf.urls import patterns, include, url
from django.conf import settings


urlpatterns = patterns('',
                       url(r'accounts/', include('accounts.urls')),
                       url(r'dashboard/', include('dashboard.urls')),
                       url(r'departments/', include('departments.urls')),
                       url(r'oms_config/', include('oms_config.urls')),
                       url(r'dbs_mysql/', include('dbs_mysql.urls')),
                       url(r'dbs_redis/', include('dbs_redis.urls')),
                       url(r'repository/', include('repository.urls')),
                       url(r'assets/', include('assets.urls')),
                       url(r'saltstack/', include('saltstack.urls')),
                       url(r'^media/(?P<path>.*)$', 'django.views.static.serve',
                           {'document_root': settings.MEDIA_ROOT}),
                       )

repository/urls.py
# -*- coding:utf8 -*-

from django.conf.urls import patterns, url
from repository import views


urlpatterns = patterns('',
                       url(r'^repository_add/', views.repository_add, name='repository_add'),
                       url(r'^repository_del/', views.repository_del, name='repository_del'),
                       url(r'^repository_edit/(?P<pk>\d+)$', views.repository_edit, name='repository_edit'),
                       url(r'^repository_detail/(?P<pk>\d+)$', views.repository_detail, name='repository_detail'),
                       url(r'^repository_list/', views.repository_list, name='repository_list'),

                       # 仓库版本
                       url(r'^repo_version_add/', views.repo_version_add, name='repo_version_add'),
                       url(r'^repo_version_del/', views.repo_version_del, name='repo_version_del'),
                       url(r'^repo_version_detail/(?P<pk>\d+)$', views.repo_version_detail, name='repo_version_detail'),
                       url(r'^repo_version_list/', views.repo_version_list, name='repo_version_list'),

                       # local archive
                       url(r'^local_archive_process/', views.local_archive_process, name='local_archive_process'),

                       )

repository/models.py
# -*- coding: utf8 -*-
from django.db import models

# Create your models here.


class Repository(models.Model):
    REPO_TYPE_CHOICE = (
        (u'1', u'git'),
        (u'2', u'svn'),
    )

    REPO_PROTOCOL_CHOICE = (
        (u'1', u'ssh'),
        (u'2', u'http'),
        (u'3', u'https'),
    )

    repo_name = models.CharField(max_length=20, verbose_name=u'仓库名')
    repo_address = models.CharField(max_length=200, verbose_name=u'仓库地址')
    repo_user = models.CharField(max_length=50, verbose_name=u'仓库用户名')
    repo_pass = models.CharField(max_length=20, verbose_name=u'仓库用户密码', blank=True, null=True)
    repo_type = models.CharField(max_length=1, verbose_name=u'仓库类型', choices=REPO_TYPE_CHOICE)
    repo_protocol = models.CharField(max_length=1, verbose_name=u'使用协议', choices=REPO_PROTOCOL_CHOICE)
    repo_tag = models.CharField(max_length=20, verbose_name=u'仓库标识')

    class Meta:
        permissions = (
            ('view_repository', 'Can view repository'),
        )

    def __unicode__(self):
        return self.repo_name


class Version(models.Model):

    VERSION_STATIC_CHOICE = (
        (u'0', u'disable'),
        (u'1', u'release'),
        (u'2', u'backup'),
        (u'3', u'rollback'),
    )

    project = models.CharField(max_length=20, verbose_name=u'项目名', blank=True)
    version = models.CharField(max_length=20, verbose_name=u'版本号', unique=True)
    timestamp = models.DateTimeField(verbose_name=u'时间')
    author = models.CharField(max_length=20, verbose_name=u'提交用户')
    vernier = models.CharField(max_length=1, verbose_name=u'游标', choices=VERSION_STATIC_CHOICE)
    content = models.TextField(verbose_name=u'备注')

    class Meta:
        permissions = (
            ('view_version', 'Can view repo version'),
        )

    def __unicode__(self):
        return '%s | %s' % (self.project, self.version)

repository/forms.py
# --*-- coding:utf8 --*--

from django import forms
from models import Repository, Version
from departments.models import Department


class RepositoryForm(forms.ModelForm):

    class Meta:
        model = Repository
        fields = '__all__'


class VersionForm(forms.ModelForm):
    # department = forms.ModelChoiceField(label=u'项目组', queryset=Department.objects.all())
    project = forms.CharField(max_length=20, label=u'项目', widget=forms.HiddenInput(), required=False)
    repository = forms.ModelChoiceField(label=u'仓库', queryset=Repository.objects.all())
    archive_path = forms.CharField(max_length=200, label=u'本地归档路径', initial=u'/srv/salt/code/project/')
    version = forms.CharField(max_length=20, label=u'版本', widget=forms.HiddenInput(), required=False)
    timestamp = forms.DateTimeField(label=u'时间', widget=forms.HiddenInput(), required=False)
    author = forms.CharField(max_length=20, label=u'提交用户', widget=forms.HiddenInput(), required=False)
    vernier = forms.CharField(label=u'游标', widget=forms.HiddenInput(), required=False)
    is_backup = forms.BooleanField(label=u'是否备份', widget=forms.HiddenInput(), required=False)
    content = forms.CharField(label=u'备注', widget=forms.HiddenInput(), required=False)

    class Meta:
        model = Version
        fields = '__all__'


class LocalArchiveForm(forms.Form):
    departments = forms.ModelChoiceField(label=u'项目组', queryset=Department.objects.all())
    repository = forms.ModelChoiceField(label=u'仓库', queryset=Repository.objects.all())
    archive_path = forms.CharField(max_length=200, label=u'本地归档路径', initial=u'/srv/salt/code/project/')

    # def clean(self):
    #     cleaned_data = super(LocalArchiveForm, self).clean()
    #     return cleaned_data

repository/views.py
# -*- coding:utf8 -*-

from django.shortcuts import render, get_object_or_404, redirect
from django.shortcuts import HttpResponse, Http404
from models import Repository, Version
from forms import RepositoryForm, VersionForm, LocalArchiveForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth.decorators import permission_required
from saltstack.scripts.get_newVersion_from_gitLog import get_version
# from saltstack.scripts.create_folder import makedir_p
from saltstack.scripts.repo_process import *
# from saltstack.scripts.re_match_result import *
import os


@login_required(login_url='/accounts/login/')
@permission_required('repository.view_repository', raise_exception=True)
def repository_list(request, template_name='repository/repository_list.html'):
    username = request.session['username']
    repo_list = Repository.objects.all()
    var6 = 'active'
    highlight1 = 'active'
    return render(request, template_name, locals())


@login_required(login_url='/accounts/login/')
@permission_required('repository.add_repository', raise_exception=True)
def repository_add(request, template_name='repository/repository_add.html'):
    form = RepositoryForm(request.POST or None)
    username = request.session['username']
    var6 = 'active'
    if form.is_valid():
        form.save()
        return redirect('repository_list')

    return render(request, template_name, {'form': form,
                                           'var6': var6,
                                           'username': username,
                                           'highlight1': 'active',
                                           })


@login_required(login_url='/accounts/login/')
@permission_required('repository.change_repository', raise_exception=True)
def repository_edit(request, pk,  template_name='repository/repository_add.html'):
    repository = get_object_or_404(Repository, pk=pk)
    username = request.session['username']
    form = RepositoryForm(request.POST or None, instance=repository)
    if form.is_valid():
        form.save()
        return redirect('repository_list')

    return render(request, template_name, {'form': form,
                                           'var6': 'active',
                                           'username': username,
                                           'repository': repository,
                                           'highlight1': 'active',
                                           })


@login_required(login_url='/accounts/login/')
@permission_required('repository.delete_repository', raise_exception=True)
def repository_del(request):
    pk = request.GET['id']
    repository = get_object_or_404(Repository, pk=int(pk))
    repository.delete()
    return HttpResponse('delete success')


@login_required(login_url='/accounts/login/')
@permission_required('repository.view_assets', raise_exception=True)
def repository_detail(request, pk, template_name='repository/repository_detail.html'):
    try:
        repository = Repository.objects.get(pk=pk)
    except Repository.DoesNotExist:
        raise Http404
    return render(request, template_name, {'repository': repository,
                                           'var6': 'active',
                                           'username': request.session['username'],
                                           'highlight1': 'active',
                                           })


@login_required(login_url='/accounts/login/')
@permission_required('repository.view_version', raise_exception=True)
def repo_version_list(request, template_name='repository/repo_version_list.html'):
    username = request.session['username']
    versions = Version.objects.all()
    var6 = 'active'
    highlight2 = 'active'
    return render(request, template_name, locals())


@login_required(login_url='/accounts/login/')
@permission_required('repository.add_version', raise_exception=True)
def repo_version_add(request, template_name='repository/repo_version_add.html'):
    form = VersionForm(request.POST or None)
    username = request.session['username']
    if form.is_valid():
        project_name = form.cleaned_data['repository'].repo_tag
        print project_name
        archive_path = os.path.join(form.cleaned_data['archive_path'], project_name)
        version = get_version(archive_path)
        if not version:
            return HttpResponse("Your configuration specifies to merge with the ref 'master' from the remote, "
                                "but no such ref was fetched.")
        if Version.objects.filter(version=version[0]):
            return HttpResponse("already exist.")
        else:
            version_object = Version(project=project_name, version=version[0], timestamp=version[1],
                                     author=version[2], content=version[3], vernier=u'0')
            version_object.save()

        return redirect('repo_version_list')

    return render(request, template_name, {'form': form,
                                           'var6': 'active',
                                           'username': username,
                                           'highlight2': 'active',
                                           })


@login_required(login_url='/accounts/login/')
@permission_required('repository.delete_version', raise_exception=True)
def repo_version_del(request):
    pk = request.GET['id']
    print pk
    versions = get_object_or_404(Version, pk=int(pk))
    versions.delete()
    return HttpResponse('delete success')


@login_required(login_url='/accounts/login/')
@permission_required('repository.view_version', raise_exception=True)
def repo_version_detail(request, pk, template_name='repository/repo_version_detail.html'):
    try:
        versions = Version.objects.get(pk=pk)
    except Version.DoesNotExist:
        raise Http404
    return render(request, template_name, {'versions': versions,
                                           'var6': 'active',
                                           'username': request.session['username'],
                                           'highlight2': 'active',
                                           })


@login_required(login_url='/accounts/login/')
@permission_required('repository.view_version', raise_exception=True)
def local_archive_process(request, template_name='repository/local_archive_process.html'):
    form = LocalArchiveForm(request.POST or None)
    if form.is_valid():
        project = form.cleaned_data['repository'].repo_tag
        archive_path = form.cleaned_data['archive_path']
        repository = form.cleaned_data['repository']
        # print project
        # print archive_path
        # print repository.repo_user, repository.repo_pass, repository.repo_address

        # archive_abs_path = os.path.join(archive_path, project)
        # if not os.path.exists(archive_abs_path):
        #     makedir_p(archive_path)

        repository_url = get_repo_url(repository)
        content = git_checkout(archive_path, project, repository_url)
        if content:
            return redirect('repo_version_list')
        else:
            return HttpResponse("Failed")

    return render(request, template_name, {'form': form})

templates/repository/local_archive_process.html
{% extends 'base.html' %}
{% block content %}
    <div class="row wrapper border-bottom white-bg page-heading">
        <div class="col-lg-10">
            <h2>本地归档</h2>
            <ol class="breadcrumb">
                <li>
                    <a href="{% url 'dashboard' %}">Home</a>
                </li>
                <li>
                    <a href="{% url 'repo_version_list' %}">版本管理</a>
                </li>

                <li class="{{ var6 }}">
                    <strong>本地归档</strong>
                </li>
            </ol>
        </div>
        <div class="col-lg-2">

        </div>
    </div>

    <div class="row">
        <div class="col-lg-12">
            <div class="ibox float-e-margins">
                <div class="ibox-title">
                    <h5>本地归档</h5>
                    <div class="ibox-tools">
                        <a class="collapse-link">
                            <i class="fa fa-chevron-up"></i>
                        </a>
                        <a class="close-link">
                            <i class="fa fa-times"></i>
                        </a>
                    </div>
                </div>
                <div class="ibox-content">
                    <form method="post">
                        <ul>{% csrf_token %}
                            {{ form.as_p }}
                            <input class="btn btn-info" type="submit" value="提交" />
                        </ul>
                    </form>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

templates/repository/repository_add.html
{% extends 'base.html' %}
{% block content %}
    <div class="row wrapper border-bottom white-bg page-heading">
        <div class="col-lg-10">
            <h2>添加仓库</h2>
            <ol class="breadcrumb">
                <li>
                    <a href="{% url 'dashboard' %}">Home</a>
                </li>
                <li>
                    <a href="{% url 'repository_list' %}">仓库管理</a>
                </li>

                <li class="{{ var6 }}">
                    <strong>添加仓库</strong>
                </li>
            </ol>
        </div>
        <div class="col-lg-2">

        </div>
    </div>

    <div class="row">
        <div class="col-lg-12">
            <div class="ibox float-e-margins">
                <div class="ibox-title">
                    <h5>添加仓库</h5>
                    <div class="ibox-tools">
                        <a class="collapse-link">
                            <i class="fa fa-chevron-up"></i>
                        </a>
                        <a class="close-link">
                            <i class="fa fa-times"></i>
                        </a>
                    </div>
                </div>
                <div class="ibox-content">
                    <form method="post" class="form-horizontal">{% csrf_token %}
                        <div class="form-group">
                            <label class="col-sm-2 control-label">仓库名</label>

                            <div class="col-sm-10">
                                <input id="id_repo_name" name="repo_name" type="text" class="form-control"
                                       value="{{ repository.repo_name }}">
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="col-sm-2 control-label">仓库地址</label>
                            <div class="col-sm-10">
                                <input id="id_repo_address" name="repo_address" type="text" class="form-control"
                                       value="{{ repository.repo_address }}">
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="col-sm-2 control-label">仓库用户</label>
                            <div class="col-sm-10">
                                <input id="id_repo_user" name="repo_user" type="text" class="form-control"
                                       value="{{ repository.repo_user }}">
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="col-sm-2 control-label">仓库密码</label>
                            <div class="col-sm-10">
                                    <input id="id_repo_pass" name="repo_pass" type="text" class="form-control"
                                           value="{{ repository.repo_pass }}">
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="col-sm-2 control-label">仓库标识</label>
                            <div class="col-sm-10">
                                    <input id="id_repo_tag" name="repo_tag" type="text" class="form-control"
                                           value="{{ repository.repo_tag }}">
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="col-sm-2 control-label">仓库类型</label>
                                <div class="col-sm-10">
                                    <label>
                                        <select class="form-control m-b" id="id_repo_type" name="repo_type">
                                            {% if repository.get_repo_type_display == 'git' %}
                                                <option value="1" selected>git</option>
                                            {% elif repository.get_repo_type_display == 'svn' %}
                                                <option value="2" selected>svn</option>
                                            {% else %}
                                                <option value="0">-------------请选择--------------</option>
                                                <option value="1">git</option>
                                                <option value="2">svn</option>
                                            {% endif %}
                                        </select>
                                    </label>
                                </div>
                        </div>

                        <div class="form-group">
                            <label class="col-sm-2 control-label">传输协议</label>
                                <div class="col-sm-10">
                                    <label>
                                        <select class="form-control m-b" id="id_repo_protocol" name="repo_protocol">
                                            {% if repository.get_repo_protocol_display == 'ssh' %}
                                                <option value="1" selected>ssh</option>
                                            {% elif repository.get_repo_protocol_display == 'http' %}
                                                <option value="2" selected>http</option>
                                            {% elif repository.get_repo_protocol_display == 'https' %}
                                                <option value="3" selected>https</option>
                                            {% else %}
                                                <option value="0">-------------请选择--------------</option>
                                                <option value="1">ssh</option>
                                                <option value="2">http</option>
                                                <option value="3">https</option>
                                            {% endif %}
                                        </select>
                                    </label>
                                </div>
                        </div>

                        <div class="hr-line-dashed"></div>

                        <div class="form-group">
                            <div class="col-sm-4 col-sm-offset-2">
                                <button class="btn btn-white" type="submit">取消</button>
                                <button class="btn btn-primary" type="submit">保存</button>
                            </div>
                        </div>

                    </form>

                </div>
            </div>
        </div>
    </div>

{% endblock %}

templates/repository/repository_detail.html
{% extends 'base.html' %}
{% block content %}
    <div class="row wrapper border-bottom white-bg page-heading">
        <div class="col-sm-4">
            <h2>仓库详情</h2>
            <ol class="breadcrumb">
                <li>
                    <a href="{% url 'dashboard' %}">Home</a>
                </li>
                <li class="{{ var8 }}">
                    <strong><a href="{% url 'dbs_list' %}">MySQL</a></strong>
                </li>
                <li class="{{ var8 }}">
                    <strong>仓库详情</strong>
                </li>
            </ol>
        </div>
    </div>
        <div class="row">
            <div class="col-lg-9">
                <div class="wrapper wrapper-content animated fadeInUp">
                    <div class="ibox">
                        <div class="ibox-content">
                            <div class="row">
                                <div class="col-lg-12">
                                    <div class="m-b-md">
                                        <h2>仓库详情页</h2>
                                    </div>
                                    <dl class="dl-horizontal">
                                        <dt>Status:</dt><dd><span class="label label-primary">可用</span></dd>
                                    </dl>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-lg-5">
                                    <dl class="dl-horizontal">

                                        <dt>仓库名:</dt> <dd>{{ repository.repo_name }}</dd>
                                        <dt>仓库地址:</dt> <dd>{{ repository.repo_address }}</dd>
                                        <dt>仓库用户:</dt> <dd>{{ repository.repo_user }}</dd>
                                        <dt>仓库密码:</dt> <dd>{{ repository.repo_pass }}</dd>
                                        <dt>仓库类型:</dt> <dd>{{ repository.get_repo_type_display }}</dd>
                                        <dt>传输协议:</dt> <dd>{{ repository.get_repo_protocol_display }}</dd>
                                        <dt>公司:</dt> <dd><a href="#" class="text-navy"> Leshu Company</a> </dd>
                                        <!--<dt>程序迭代版本:</dt> <dd> 	v1.4.2 </dd>-->
                                    </dl>
                                </div>
{#                                <div class="col-lg-7" id="cluster_info">#}
{#                                    <dl class="dl-horizontal" >#}
{##}
{#                                        <dt>用户名:</dt> <dd>{{ db_accounts.db_username }}</dd>#}
{#                                        <dt>密码:</dt> <dd>{{ db_accounts.db_password }}</dd>#}
{#                                        <dt>密码:</dt> <dd> 	10.07.2014 23:36:57 </dd>#}
{#                                        <dt>Participants:</dt>#}
{#                                        <dd class="project-people">#}
{#                                        <a href=""><img alt="image" class="img-circle" src="img/a3.jpg"></a>#}
{#                                        <a href=""><img alt="image" class="img-circle" src="img/a1.jpg"></a>#}
{#                                        <a href=""><img alt="image" class="img-circle" src="img/a2.jpg"></a>#}
{#                                        <a href=""><img alt="image" class="img-circle" src="img/a4.jpg"></a>#}
{#                                        <a href=""><img alt="image" class="img-circle" src="img/a5.jpg"></a>#}
{#                                        </dd>#}
{#                                    </dl>#}
{#                                </div>#}

                                <!--<div class="row">
                                    <div class="col-lg-12">
                                        <dl class="dl-horizontal">
                                            <dt>Completed:</dt>
                                            <dd>
                                                <div class="progress progress-striped active m-b-sm">
                                                    <div style="width: 100%;" class="progress-bar"></div>
                                                </div>
                                                <small>项目组设置完成度<strong>100%</strong></small>
                                            </dd>
                                        </dl>
                                    </div>
                                </div>-->
                            </div>
                        </div>
                    </div>
                </div>
            </div>

        <div class="col-lg-3">
                <div class="wrapper wrapper-content project-manager">
                    <h4>描述</h4>
{#                    <img src="img/zender_logo.png" class="img-responsive">#}
                    <p class="small">
                        Mysql相关设置
                    </p>
                    <p class="small font-bold">
                        <span><i class="fa fa-circle text-warning"></i> High priority</span>
                    </p>
                    <h5>项目标签</h5>
                    <ul class="tag-list" style="padding: 0">
                        <li><a href=""><i class="fa fa-tag"></i> {{ repository.repo_name }}</a></li>
                    </ul>
                </div>
            </div>
    </div>

{% endblock %}

templates/repository/repository_list.html
{% extends 'base.html' %}
{% block content %}
    <div class="row wrapper border-bottom white-bg page-heading">
        <div class="col-lg-10">
            <h2>仓库管理</h2>
            <ol class="breadcrumb">
                <li>
                    <a href="{% url 'dashboard' %}">Home</a>
                </li>
                <li class={{ var6 }}>
                    <strong>仓库管理</strong>
                </li>
            </ol>
        </div>
        <div class="col-lg-2">
        </div>
    </div>
    <div class="wrapper wrapper-content animated fadeInRight">
        <div class="row">
            <div class="col-lg-12">
                <div class="ibox float-e-margins">
                    <div class="ibox-title">
                        <!--<h5>Basic Data Tables example with responsive plugin</h5>-->
                        <a href="{% url 'repository_add' %}" class="btn btn-primary">添加仓库</a>
                        <div class="ibox-tools">
                            <a class="collapse-link">
                                <i class="fa fa-chevron-up"></i>
                            </a>
                            <a class="close-link">
                                <i class="fa fa-times"></i>
                            </a>
                        </div>
                    </div>
                    <div class="ibox-content">
                        <div class="table-responsive">
                            <table class="table table-striped table-bordered table-hover dataTables-example"
                                   id="repo_list" >
                                <thead>
                                <tr>
                                    <!--<th>多选</th>-->
                                    <th>仓库名</th>
                                    <th>仓库用户</th>
                                    <th>仓库地址</th>
                                    <th>仓库类型</th>
                                    <th>使用协议</th>
                                    <th>操作</th>
                                </tr>
                                </thead>
                                <tbody>
                                    {% for item in repo_list %}
                                        <tr class="gradeX">
                                            <td>{{ item.repo_name }}</td>
                                            <td>{{ item.repo_user }}</td>
                                            <td>{{ item.repo_address }}</td>
                                            <td>{{ item.get_repo_type_display }}</td>
                                            <td>{{ item.get_repo_protocol_display }}</td>
                                            <td>
                                                <a class="btn btn-info" href="{% url "repository_edit" item.id %}">编辑</a>
                                                <a href="javascript:void(0);" deleteId="{{ item.id }}" class="btn btn-danger">删除</a>
                                                <a class="btn btn-primary" href="{% url 'repository_detail' item.id %}">详情</a></td>
                                        </tr>
                                    {% endfor %}
                                </tbody>
                                <tfoot>
                                <tr>
                                    <!--<th>多选</th>-->
                                    <th>仓库名</th>
                                    <th>仓库用户</th>
                                    <th>仓库地址</th>
                                    <th>仓库类型</th>
                                    <th>使用协议</th>
                                    <th>操作</th>
                                </tr>
                                </tfoot>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock %}