OMS/urls.py
from django.conf.urls import patterns, include, url
from django.conf import settings


urlpatterns = patterns('',
                       url(r'accounts/', include('accounts.urls')),
                       url(r'dashboard/', include('dashboard.urls')),
                       url(r'departments/', include('departments.urls')),
                       url(r'oms_config/', include('oms_config.urls')),
                       url(r'dbs_mysql/', include('dbs_mysql.urls')),
                       url(r'dbs_redis/', include('dbs_redis.urls')),
                       url(r'repository/', include('repository.urls')),
                       url(r'assets/', include('assets.urls')),
                       url(r'saltstack/', include('saltstack.urls')),
                       url(r'^media/(?P<path>.*)$', 'django.views.static.serve',
                           {'document_root': settings.MEDIA_ROOT}),
                       )

accounts/urls.py
from django.conf.urls import patterns, url
from accounts import views


urlpatterns = patterns('',
                       url(r'login/', views.login, name='user_login'),
                       url(r'logout/', views.logout, name='user_logout'),
                       url(r'user_list/', views.user_list, name='user_list'),
                       url(r'user_add/', views.user_add, name='user_add'),
                       url(r'user_edit/(?P<pk>\d+)$', views.user_edit, name='user_edit'),
                       url(r'user_detail/(?P<pk>\d+)$', views.user_detail, name='user_detail'),
                       url(r'user_delete/', views.user_delete, name='user_delete'),
                       url(r'group_add/', views.group_add, name='group_add'),
                       url(r'group_list/', views.group_list, name='group_list'),
                       url(r'group_edit/(?P<pk>\d+)$', views.group_edit, name='group_edit'),
                       url(r'group_detail/(?P<pk>\d+)$', views.group_detail, name='group_detail'),
                       url(r'group_delete/', views.group_delete, name='group_delete'),
                       url(r'permission_list/', views.permissions_list, name='permissions_list'),
                       url(r'password_reset/(?P<pk>\d+)$', views.password_reset, name='password_reset'),
                       url(r'user_summary/', views.user_summary, name='user_summary'),
                       )

accounts/models.py
from django.db import models
# from django.contrib.auth.models import User
from django.contrib.auth.models import AbstractUser

# Create your models here.


class User(AbstractUser):
    address1 = models.CharField(max_length=50, blank=True, null=True)
    address2 = models.CharField(max_length=50, blank=True, null=True)
    city = models.CharField(max_length=50, blank=True, null=True)
    state = models.CharField(max_length=50, blank=True, null=True)
    mobile = models.CharField(max_length=32, blank=True, null=True)
    home = models.CharField(max_length=32, blank=True, null=True)
    job = models.CharField(max_length=32, blank=True, null=True)

    def __unicode__(self):
        return self.username

assets/models.py
# --*-- coding: utf-8 --*--

from django.db import models
from departments.models import Department
from oms_config.models import Zone

# Create your models here.


class Hardware(models.Model):
    UNIT_CHOICES = (
        (u'1', u'GB'),
        (u'2', u'Core'),
    )

    name = models.CharField(max_length=20, blank=True, null=True, verbose_name=u'硬件名')
    value = models.IntegerField(blank=True, null=True, verbose_name=u'硬件值')
    unit = models.CharField(max_length=10, blank=True, null=True, choices=UNIT_CHOICES, verbose_name=u'单位')

    class Meta:
        permissions = (
            ('view_hardware', 'Can view Hardware'),
        )

    def __unicode__(self):
        return '%s %s %s' % (self.name, self.value, self.get_unit_display())


class Network(models.Model):
    NET_TYPE_CHOICES = (
        (u'1', u'BGP'),
        (u'2', u'电信'),
        (u'3', u'联通'),
        (u'4', u'移动'),
        (u'5', u'教育'),
        (u'6', u'内网'),
    )

    UNIT_CHOICES = (
        (u'1', u'Mbps'),
    )

    public_address = models.IPAddressField(blank=True, null=True, verbose_name=u'公网地址')
    private_address = models.IPAddressField(blank=True, null=True, verbose_name=u'内网地址')
    bandwidth = models.IntegerField(blank=True, null=True, verbose_name=u'带宽')
    provide = models.CharField(max_length=20, verbose_name=u'接入商', blank=True, null=True)
    net_type = models.CharField(max_length=20, blank=True, null=True, verbose_name=u'网络类型', choices=NET_TYPE_CHOICES)
    unit = models.CharField(max_length=10, blank=True, null=True, verbose_name=u'单位', choices=UNIT_CHOICES)
    bind = models.BooleanField(default=False, verbose_name=u'绑定', blank=True)

    class Meta:
        permissions = (
            ('view_network', 'Can view network'),
        )

    def __unicode__(self):
        return '%s %s %s %s %s %s' % (self.public_address, self.private_address, self.provide,
                                      self.net_type, self.bandwidth, self.get_unit_display())


class Services(models.Model):
    name = models.CharField(max_length=50, verbose_name=u'服务名')
    port = models.IntegerField(verbose_name=u'端口', blank=True, null=True)

    class Meta:
        permissions = (
            ('view_service', 'can view services'),
        )

    def __unicode__(self):
        return self.name


class Tag(models.Model):
    name = models.CharField(max_length=20, verbose_name=u'标签名', blank=True, null=True, unique=True)

    class Meta:
        permissions = (
            ('view_tag', 'Can view tags'),
        )

    def __unicode__(self):
        return self.name


class Assets(models.Model):
    HOST_TYPE_CHOICES = (
        (u'1', u'物理机'),
        (u'2', u'云主机'),
        (u'3', u'虚拟机'),
    )

    OS_CHOICES = (
        (u'1', u'CentOS 7.2 X86 64bit'),
        (u'2', u'CentOS 7.0 x86 64bit'),
        (u'3', u'CentOS 6.5 x86 64bit'),
    )

    host_name = models.CharField(max_length=50, verbose_name=u'主机名', unique=True)
    alias_name = models.CharField(max_length=100, verbose_name=u'可见名', blank=True, null=True)
    host_type = models.CharField(max_length=10, blank=True, null=True,
                                 choices=HOST_TYPE_CHOICES, verbose_name=u'主机类型')
    tag = models.ManyToManyField(Tag, verbose_name=u'标识')
    game_zone = models.ManyToManyField(Zone, verbose_name=u'游戏区')
    os = models.CharField(max_length=10, blank=True, null=True,
                          choices=OS_CHOICES, verbose_name=u'操作系统')
    superuser = models.CharField(max_length=20, verbose_name=u'管理员', default=u'root')
    superuser_pass = models.CharField(max_length=50, verbose_name=u'管理员密码', blank=True, null=True)
    is_online = models.BooleanField(blank=True, default=False, verbose_name=u'在线')
    is_unused = models.BooleanField(verbose_name=u'闲置', default=False)
    is_master = models.BooleanField(blank=True, default=False, verbose_name=u'salt-master')
    is_minion = models.BooleanField(blank=True, default=False, verbose_name=u'salt-minion')
    hardware = models.ManyToManyField(Hardware, verbose_name=u'硬件配置')
    networks = models.OneToOneField(Network, on_delete=models.CASCADE, verbose_name=u'网络', related_name='assets')
    departments = models.ForeignKey(Department, on_delete=models.CASCADE, verbose_name=u'业务组', blank=True, null=True)
    services = models.ManyToManyField(Services, verbose_name=u'运行的服务')

    class Meta:
        permissions = (
            ('view_assets', 'Can view assets'),
        )

    def __unicode__(self):
        return self.alias_name


class SysUser(models.Model):
    servers = models.ForeignKey(Assets, verbose_name=u'服务器')
    sys_user = models.CharField(max_length=50, verbose_name=u'用户', blank=True, null=True)
    sys_pass = models.CharField(max_length=200, verbose_name=u'密码', blank=True, null=True)

    class Meta:
        permissions = (
            ('view_sysuser', 'can view sys user information'),
        )

    def __unicode__(self):
        return '%s %s' % (self.sys_user, self.sys_pass)

accounts/forms.py
# --*-- coding:utf-8 --*--

from django import forms
from django.contrib.auth.models import Group, Permission
from models import User


class LoginUserForm(forms.Form):
    username = forms.CharField(
            label=u"登陆帐号",
            error_messages={'required': u'帐号不能为空'},
            widget=forms.TextInput(attrs={'placeholder': u"登陆帐号",}),
    )
    password = forms.CharField(
            label=u"密码",
            error_messages={'required': u'密码不能为空'},
            widget=forms.PasswordInput(attrs={'placeholder': u"密码",})
    )

    def clean_all(self):
        if not self.is_valid():
            raise forms.ValidationError(u"用户名和密码为必填项")
        else:
            cleaned_data = super(LoginUserForm, self).clean()
        return cleaned_data


class UserForm(forms.ModelForm):
    username = forms.RegexField(regex=r'^[\w.@+-]+$',
                                max_length=30,
                                label=u"登陆帐号",
                                error_messages={'invalid': u"这个值仅可以包含字母,数字和@/./+/-/_字符."})
    password1 = forms.CharField(widget=forms.PasswordInput,
                                label=u"密码")
    password2 = forms.CharField(widget=forms.PasswordInput,
                                label=u"密码(again)")

    class Meta:
        model = User
        fields = ['username', 'password1', 'password2']

    def clean_username(self):
        existing = User.objects.filter(username__iexact=self.cleaned_data['username'])
        if existing.exists():
            raise forms.ValidationError("此用户名已经存在.")
        else:
            return self.cleaned_data['username']

    def clean_email(self):
        if User.objects.filter(email__iexact=self.cleaned_data['email']):
            raise forms.ValidationError(
                    "这个邮箱地址已被使用. 请提供不同的邮箱地址."
            )
        return self.cleaned_data['email']

    def clean_password(self):
        if 'password1' in self.cleaned_data and 'password2' in self.cleaned_data:
            if self.cleaned_data['password1'] != self.cleaned_data['password2']:
                raise forms.ValidationError("两次输入密码不一致.")
        return self.cleaned_data


class EditUserForm(forms.ModelForm):

    class Meta:
        model = User
        fields = '__all__'


class GroupForm(forms.ModelForm):
    class Meta:
        model = Group
        fields = '__all__'


class PermissionsForm(forms.ModelForm):
    class Meta:
        model = Permission
        fields = '__all__'


class SetPasswordForm(forms.Form):
    old_password = forms.CharField(label=u'原密码', error_messages={'required': u'请输入原密码'},
                                   widget=forms.PasswordInput(attrs={'placeholder': u'原密码',}),)
    new_password = forms.CharField(label=u'新密码', error_messages={'required': u'请输入新密码'},
                                   widget=forms.PasswordInput(attrs={'placeholder': u'新密码'}),)
    verify_password = forms.CharField(label=u'确认密码', error_messages={'required': u'请再一次输入新密码'},
                                      widget=forms.PasswordInput(attrs={'placeholder': u'确认密码',}),)

    def clean(self):
        if not self.is_valid():
            raise forms.ValidationError(u'所有项都为必填')
        elif self.cleaned_data['new_password'] != self.cleaned_data['verify_password']:
            raise forms.ValidationError(u'输入密码不一致')
        else:
            cleaned_data = super(SetPasswordForm, self).clean()
        return cleaned_data

templates/accounts/group_add.html
{% extends 'base.html' %}
{% block content %}
    <div class="row wrapper border-bottom white-bg page-heading">
        <div class="col-lg-10">
            <h2>添加组</h2>
            <ol class="breadcrumb">
                <li>
                    <a href="{% url 'dashboard' %}">Home</a>
                </li>
                <li>
                    <a href="{% url 'group_list' %}">权限组</a>
                </li>
                <li class="{{ var2 }}">
                    <strong>添加组</strong>
                </li>
            </ol>
        </div>
        <div class="col-lg-2">

        </div>
    </div>

    <div class="row">
        <div class="col-lg-12">
            <div class="ibox float-e-margins">
                <div class="ibox-title">
                    <h5>添加用户权限组 </h5>
                    <div class="ibox-tools">
                        <a class="collapse-link">
                            <i class="fa fa-chevron-up"></i>
                        </a>
                        <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                            <i class="fa fa-wrench"></i>
                        </a>
                        <ul class="dropdown-menu dropdown-user">
                            <li><a href="#">Config option 1</a>
                            </li>
                            <li><a href="#">Config option 2</a>
                            </li>
                        </ul>
                        <a class="close-link">
                            <i class="fa fa-times"></i>
                        </a>
                    </div>
                </div>
                <div class="ibox-content">
                    <form method="post" class="form-horizontal">{% csrf_token %}
                        <div class="form-group">
                            {{ form.as_p }}
                            <input type="submit" value="Submit" />
                        </div>
                    </form>

{#                    <form method="post" class="form-horizontal">{% csrf_token %}#}
{#                        <div class="form-group">#}
{#                            <label class="col-sm-2 control-label">组名</label>#}
{#                            <div class="col-sm-10">#}
{#                                <label>#}
{#                                    <input id="id_name" name="name" type="text" class="form-control" value="{{ group }}">#}
{#                                </label>#}
{#                            </div>#}
{#                        </div>#}
{##}
{#                        <div class="form-group">#}
{#                            <label class="col-sm-2 control-label" for="id_permissions">权限</label>#}
{#                                <div class="col-lg-4 m-l-n">#}
{#                                    <select class="form-control" multiple="multiple" id="id_permissions" name="permissions">#}
{#                                        {% if user.is_authenticated %}#}
{#                                            {% for permission in permission_list %}#}
{#                                                {% if permission in group.permissions.all %}#}
{#                                                    <option id="{{ permission.id }}" selected>{{ permission }}</option>#}
{#                                                {% else %}#}
{#                                                    <option>{{ permission }}</option>#}
{#                                                {% endif %}#}
{#                                            {% endfor %}#}
{#                                        {% endif %}#}
{#                                    </select><br />#}
{#                                    <small>Hold down "Control", or "Command" on a Mac, to select more than one.</small>#}
{#                                </div>#}
{#                        </div>#}
{#                        <div class="hr-line-dashed"></div>#}
{##}
{#                        <div class="form-group">#}
{#                            <div class="col-sm-4 col-sm-offset-2">#}
{#                                <button class="btn btn-white" type="submit">取消</button>#}
{#                                <button class="btn btn-primary" type="submit">保存</button>#}
{#                            </div>#}
{#                        </div>#}

{#                    <input class="btn btn-info" type="submit" value="Submit" />#}

{#                    </form>#}

                </div>
            </div>
        </div>
    </div>

{% endblock %}

templates/accounts/group_detail.html
{% extends 'base.html' %}
{% block content %}
    <div class="row wrapper border-bottom white-bg page-heading">
        <div class="col-sm-4">
            <h2>详情</h2>
            <ol class="breadcrumb">
                <li>
                    <a href="{% url 'dashboard' %}">Home</a>
                </li>
                <li class="{{ var1 }}">
                    <strong><a href="{% url 'group_list' %}">用户组</a></strong>
                </li>
                <li class="{{ var1 }}">
                    <strong>详情页</strong>
                </li>
            </ol>
        </div>
    </div>
        <div class="row">
            <div class="col-lg-9">
                <div class="wrapper wrapper-content animated fadeInUp">
                    <div class="ibox">
                        <div class="ibox-content">
                            <div class="row">
                                <div class="col-lg-12">
                                    <div class="m-b-md">
{#                                        <a href="{% url 'department_edit'  %}" class="btn btn-white btn-xs pull-right">编辑</a>#}
                                        <h2>用户组详情页</h2>
                                    </div>
                                    <dl class="dl-horizontal">
                                        <dt>Status:</dt><dd><span class="label label-primary">可用</span></dd>
                                    </dl>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-lg-5">
                                    <dl class="dl-horizontal">

                                        <dt>组名:</dt> <dd>{{ group.name }}</dd>
                                        <dt>权限:</dt> <dd style="width: 100%;">{% for item in group.permissions.all %}<p>{{ item }}</p>{% endfor %}</dd>
                                        <dt>公司:</dt> <dd style="width: 100%;"><a href="#" class="text-navy"> Leshu Company</a> </dd>
{#                                        <dt>程序迭代版本:</dt> <dd> 	v1.4.2 </dd>#}
                                    </dl>
                                </div>
{#                                <div class="col-lg-7" id="cluster_info">#}
{#                                    <dl class="dl-horizontal" >#}

{#                                        <dt>最近编辑:</dt> <dd>16.08.2014 12:15:57</dd>#}
{#                                        <dt>创建时间:</dt> <dd> 	10.07.2014 23:36:57 </dd>#}
{#                                        <dt>Participants:</dt>#}
{#                                        <dd class="project-people">#}
{#                                        <a href=""><img alt="image" class="img-circle" src="img/a3.jpg"></a>#}
{#                                        <a href=""><img alt="image" class="img-circle" src="img/a1.jpg"></a>#}
{#                                        <a href=""><img alt="image" class="img-circle" src="img/a2.jpg"></a>#}
{#                                        <a href=""><img alt="image" class="img-circle" src="img/a4.jpg"></a>#}
{#                                        <a href=""><img alt="image" class="img-circle" src="img/a5.jpg"></a>#}
{#                                        </dd>#}
{#                                    </dl>#}
{#                                </div>#}

{#                                <div class="row">#}
{#                                    <div class="col-lg-12">#}
{#                                        <dl class="dl-horizontal">#}
{#                                            <dt>Completed:</dt>#}
{#                                            <dd>#}
{#                                                <div class="progress progress-striped active m-b-sm">#}
{#                                                    <div style="width: 100%;" class="progress-bar"></div>#}
{#                                                </div>#}
{#                                                <small>项目组设置完成度<strong>100%</strong></small>#}
{#                                            </dd>#}
{#                                        </dl>#}
{#                                    </div>#}
{#                                </div>#}
                            </div>
                        </div>
                    </div>
                </div>
            </div>

        <div class="col-lg-3">
                <div class="wrapper wrapper-content project-manager">
                    <h4>描述</h4>
{#                    <img src="img/zender_logo.png" class="img-responsive">#}
                    <p class="small">
                        OMS用户组，这里可以设置权限！
                    </p>
                    <p class="small font-bold">
                        <span><i class="fa fa-circle text-warning"></i> High priority</span>
                    </p>
                    <h5>权限标签</h5>
                    <ul class="tag-list" style="padding: 0">
                        {% for item in group.permissions.all %}
                        <li><a href=""><i class="fa fa-tag"></i>{{ item }}</a></li>
                        {% endfor %}
                    </ul>
{#                    <h5>Project files</h5>#}
{#                    <ul class="list-unstyled project-files">#}
{#                        <li><a href=""><i class="fa fa-file"></i> Project_document.docx</a></li>#}
{#                        <li><a href=""><i class="fa fa-file-picture-o"></i> Logo_zender_company.jpg</a></li>#}
{#                        <li><a href=""><i class="fa fa-stack-exchange"></i> Email_from_Alex.mln</a></li>#}
{#                        <li><a href=""><i class="fa fa-file"></i> Contract_20_11_2014.docx</a></li>#}
{#                    </ul>#}
{#                    <div class="text-center m-t-md">#}
{#                        <a href="#" class="btn btn-xs btn-primary">Add files</a>#}
{#                        <a href="#" class="btn btn-xs btn-primary">Report contact</a>#}
{##}
{#                    </div>#}
                </div>
            </div>
    </div>

{% endblock %}

templates/accounts/group_list.html
{% extends 'base.html' %}
{% block content %}
    <div class="row wrapper border-bottom white-bg page-heading">
        <div class="col-lg-10">
            <h2>用户组</h2>
            <ol class="breadcrumb">
                <li>
                    <a href="{% url 'dashboard' %}">Home</a>
                </li>

                <li>
                    <a>权限组管理</a>
                </li>

                <li class={{ var2 }}>
                    <strong>用户组</strong>
                </li>
            </ol>
        </div>
        <div class="col-lg-2">
        </div>
    </div>
    <div class="wrapper wrapper-content animated fadeInRight">
        <div class="row">
            <div class="col-lg-12">
                <div class="ibox float-e-margins">
                    <div class="ibox-title">
                        <!--<h5>Basic Data Tables example with responsive plugin</h5>-->
                        <a href="{% url 'group_add' %}" class="btn btn-primary">添加组</a>
                        <div class="ibox-tools">
                            <a class="collapse-link">
                                <i class="fa fa-chevron-up"></i>
                            </a>
                            <a class="close-link">
                                <i class="fa fa-times"></i>
                            </a>
                        </div>
                    </div>
                    <div class="ibox-content">
                        <div class="table-responsive">
                            <table class="table table-striped table-bordered table-hover dataTables-example" id="group_list" >
                                <thead>
                                <tr>
                                    <!--<th>多选</th>-->
                                    <th>用户组</th>
                                    <th>用户数</th>
                                    <th>操作</th>
                                </tr>
                                </thead>
                                <tbody>
                                    {% for groups in object_list %}
                                        <tr class="gradeX">
                                            <td>{{ groups.name }}</td>
                                            <td>{{ groups.user_set.count }}</td>
                                            <td>
                                                <a class="btn btn-info" href="{% url "group_edit" groups.id %}">编辑</a>
                                                <a href="javascript:void(0);" delete_id="{{ groups.id }}" class="btn btn-danger">删除</a>
                                                <a class="btn btn-primary" href="{% url 'group_detail' groups.id %}">详情</a></td>
                                        </tr>
                                    {% endfor %}
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

templates/accounts/login.html
<!DOCTYPE html>
<html>

<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <title>OMS | Login</title>

    <link href="/static/css/bootstrap.min.css" rel="stylesheet">
    <link href="/static/font-awesome/css/font-awesome.css" rel="stylesheet">

    <link href="/static/css/animate.css" rel="stylesheet">
    <link href="/static/css/style.css" rel="stylesheet">

</head>

<body class="gray-bg">

    <div class="middle-box text-center loginscreen animated fadeInDown">
        <div>
            <div>

                <h1 class="logo-name">D+</h1>

            </div>
            <h3>Welcome to OMS</h3>
            <p>运维集中化管理平台</p>
            <p>Login in. To see it in action.</p>
            {% if password_is_wrong %}
            <div class="alert alert-danger" >
                    <button type="button" class="close" data-dismiss="alert">×</button>
                    <h4>错误!</h4>用户名或密码错误
                </div>
            {% endif %}
            <form class="m-t" role="form" method="post" action="">{% csrf_token %}
                <div class="form-group">
                    <input type="text" name="username" class="form-control" placeholder="Username" required="">
                </div>
                <div class="form-group">
                    <input type="password" name="password" class="form-control" placeholder="Password" required="">
                </div>
                <button type="submit" class="btn btn-primary block full-width m-b">Login</button>

                <a href="#"><small>Forgot password?</small></a>
                <p class="text-muted text-center"><small>Do not have an account?</small></p>
                <a class="btn btn-sm btn-white btn-block" href="#">Create an account</a>
            </form>
            <p class="m-t"> <small>OMS we app framework base on Bootstrap 3 &copy; 2017</small> </p>
        </div>
    </div>

    <!-- Mainly scripts -->
    <script src="../../static/js/jquery-2.1.1.js"></script>
    <script src="../../static/js/bootstrap.min.js"></script>

</body>

</html>

templates/accounts/user_add.html
{% extends 'base.html' %}
{% block content %}
    <div class="row wrapper border-bottom white-bg page-heading">
        <div class="col-lg-10">
            <h2>添加用户</h2>
            <ol class="breadcrumb">
                <li>
                    <a href="{% url 'dashboard' %}">Home</a>
                </li>
                <li>
                    <a href="{% url 'user_list' %}">用户管理</a>
                </li>
                <li class="{{ var2 }}">
                    <strong>添加用户</strong>
                </li>
            </ol>
        </div>
        <div class="col-lg-2">

        </div>
    </div>

    <div class="row">
        <div class="col-lg-12">
            <div class="ibox float-e-margins">
                <div class="ibox-title">
                    <h5>添加用户 </h5>
                    <div class="ibox-tools">
                        <a class="collapse-link">
                            <i class="fa fa-chevron-up"></i>
                        </a>
                        <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                            <i class="fa fa-wrench"></i>
                        </a>
                        <ul class="dropdown-menu dropdown-user">
                            <li><a href="#">Config option 1</a>
                            </li>
                            <li><a href="#">Config option 2</a>
                            </li>
                        </ul>
                        <a class="close-link">
                            <i class="fa fa-times"></i>
                        </a>
                    </div>
                </div>
                <div class="ibox-content">
                    <form method="post" class="form-horizontal">{% csrf_token %}
                        <div class="form-group">
                            {{ form.as_p }}
                            <input type="submit" value="Submit" />
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

templates/accounts/user_confirm_delete.html
{% extends 'base.html' %}
{% block content %}
<form method="post">{% csrf_token %}
    你确定要删除 "{{ object }}"用户吗?
    <input type="submit" value="Submit" />
</form>

{% endblock %}

templates/accounts/user_edit.html
{% extends 'base.html' %}
{% block content %}
    <div class="row wrapper border-bottom white-bg page-heading">
        <div class="col-lg-10">
            <h2>编辑用户</h2>
            <ol class="breadcrumb">
                <li>
                    <a href="{% url 'dashboard' %}">Home</a>
                </li>
                <li>
                    <a href="{% url 'group_list' %}">用户管理</a>
                </li>
                <li class="{{ var2 }}">
                    <strong>编辑用户</strong>
                </li>
            </ol>
        </div>
        <div class="col-lg-2">

        </div>
    </div>

    <div class="row">
        <div class="col-lg-12">
            <div class="ibox float-e-margins">
                <div class="ibox-title">
                    <h5>编辑用户 </h5>
                    <div class="ibox-tools">
                        <a class="collapse-link">
                            <i class="fa fa-chevron-up"></i>
                        </a>
                        <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                            <i class="fa fa-wrench"></i>
                        </a>
                        <ul class="dropdown-menu dropdown-user">
                            <li><a href="#">修改密码</a>
                            </li>
                        </ul>
                        <a class="close-link">
                            <i class="fa fa-times"></i>
                        </a>
                    </div>
                </div>
                <div class="ibox-content">
                    <form method="post" class="form-horizontal">{% csrf_token %}
                        <div class="form-group">
                            {{ form.as_p }}
                            <input type="submit" value="Submit" />
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>

{% endblock %}