OMS/urls.py
from django.conf.urls import patterns, include, url
from django.conf import settings


urlpatterns = patterns('',
                       url(r'accounts/', include('accounts.urls')),
                       url(r'dashboard/', include('dashboard.urls')),
                       url(r'departments/', include('departments.urls')),
                       url(r'oms_config/', include('oms_config.urls')),
                       url(r'dbs_mysql/', include('dbs_mysql.urls')),
                       url(r'dbs_redis/', include('dbs_redis.urls')),
                       url(r'repository/', include('repository.urls')),
                       url(r'assets/', include('assets.urls')),
                       url(r'saltstack/', include('saltstack.urls')),
                       url(r'^media/(?P<path>.*)$', 'django.views.static.serve',
                           {'document_root': settings.MEDIA_ROOT}),
                       )

assets/models.py
# --*-- coding: utf-8 --*--

from django.db import models
from departments.models import Department
from oms_config.models import Zone

# Create your models here.


class Hardware(models.Model):
    UNIT_CHOICES = (
        (u'1', u'GB'),
        (u'2', u'Core'),
    )

    name = models.CharField(max_length=20, blank=True, null=True, verbose_name=u'硬件名')
    value = models.IntegerField(blank=True, null=True, verbose_name=u'硬件值')
    unit = models.CharField(max_length=10, blank=True, null=True, choices=UNIT_CHOICES, verbose_name=u'单位')

    class Meta:
        permissions = (
            ('view_hardware', 'Can view Hardware'),
        )

    def __unicode__(self):
        return '%s %s %s' % (self.name, self.value, self.get_unit_display())


class Network(models.Model):
    NET_TYPE_CHOICES = (
        (u'1', u'BGP'),
        (u'2', u'电信'),
        (u'3', u'联通'),
        (u'4', u'移动'),
        (u'5', u'教育'),
        (u'6', u'内网'),
    )

    UNIT_CHOICES = (
        (u'1', u'Mbps'),
    )

    public_address = models.IPAddressField(blank=True, null=True, verbose_name=u'公网地址')
    private_address = models.IPAddressField(blank=True, null=True, verbose_name=u'内网地址')
    bandwidth = models.IntegerField(blank=True, null=True, verbose_name=u'带宽')
    provide = models.CharField(max_length=20, verbose_name=u'接入商', blank=True, null=True)
    net_type = models.CharField(max_length=20, blank=True, null=True, verbose_name=u'网络类型', choices=NET_TYPE_CHOICES)
    unit = models.CharField(max_length=10, blank=True, null=True, verbose_name=u'单位', choices=UNIT_CHOICES)
    bind = models.BooleanField(default=False, verbose_name=u'绑定', blank=True)

    class Meta:
        permissions = (
            ('view_network', 'Can view network'),
        )

    def __unicode__(self):
        return '%s %s %s %s %s %s' % (self.public_address, self.private_address, self.provide,
                                      self.net_type, self.bandwidth, self.get_unit_display())


class Services(models.Model):
    name = models.CharField(max_length=50, verbose_name=u'服务名')
    port = models.IntegerField(verbose_name=u'端口', blank=True, null=True)

    class Meta:
        permissions = (
            ('view_service', 'can view services'),
        )

    def __unicode__(self):
        return self.name


class Tag(models.Model):
    name = models.CharField(max_length=20, verbose_name=u'标签名', blank=True, null=True, unique=True)

    class Meta:
        permissions = (
            ('view_tag', 'Can view tags'),
        )

    def __unicode__(self):
        return self.name


class Assets(models.Model):
    HOST_TYPE_CHOICES = (
        (u'1', u'物理机'),
        (u'2', u'云主机'),
        (u'3', u'虚拟机'),
    )

    OS_CHOICES = (
        (u'1', u'CentOS 7.2 X86 64bit'),
        (u'2', u'CentOS 7.0 x86 64bit'),
        (u'3', u'CentOS 6.5 x86 64bit'),
    )

    host_name = models.CharField(max_length=50, verbose_name=u'主机名', unique=True)
    alias_name = models.CharField(max_length=100, verbose_name=u'可见名', blank=True, null=True)
    host_type = models.CharField(max_length=10, blank=True, null=True,
                                 choices=HOST_TYPE_CHOICES, verbose_name=u'主机类型')
    tag = models.ManyToManyField(Tag, verbose_name=u'标识')
    game_zone = models.ManyToManyField(Zone, verbose_name=u'游戏区')
    os = models.CharField(max_length=10, blank=True, null=True,
                          choices=OS_CHOICES, verbose_name=u'操作系统')
    superuser = models.CharField(max_length=20, verbose_name=u'管理员', default=u'root')
    superuser_pass = models.CharField(max_length=50, verbose_name=u'管理员密码', blank=True, null=True)
    is_online = models.BooleanField(blank=True, default=False, verbose_name=u'在线')
    is_unused = models.BooleanField(verbose_name=u'闲置', default=False)
    is_master = models.BooleanField(blank=True, default=False, verbose_name=u'salt-master')
    is_minion = models.BooleanField(blank=True, default=False, verbose_name=u'salt-minion')
    hardware = models.ManyToManyField(Hardware, verbose_name=u'硬件配置')
    networks = models.OneToOneField(Network, on_delete=models.CASCADE, verbose_name=u'网络', related_name='assets')
    departments = models.ForeignKey(Department, on_delete=models.CASCADE, verbose_name=u'业务组', blank=True, null=True)
    services = models.ManyToManyField(Services, verbose_name=u'运行的服务')

    class Meta:
        permissions = (
            ('view_assets', 'Can view assets'),
        )

    def __unicode__(self):
        return self.alias_name


class SysUser(models.Model):
    servers = models.ForeignKey(Assets, verbose_name=u'服务器')
    sys_user = models.CharField(max_length=50, verbose_name=u'用户', blank=True, null=True)
    sys_pass = models.CharField(max_length=200, verbose_name=u'密码', blank=True, null=True)

    class Meta:
        permissions = (
            ('view_sysuser', 'can view sys user information'),
        )

    def __unicode__(self):
        return '%s %s' % (self.sys_user, self.sys_pass)

templates/databases/database_add.html
{% extends 'base.html' %}
{% block content %}
    <div class="row wrapper border-bottom white-bg page-heading">
        <div class="col-lg-10">
            <h2>添加数据库</h2>
            <ol class="breadcrumb">
                <li>
                    <a href="{% url 'dashboard' %}">Home</a>
                </li>
                <li>
                    <a href="{% url 'dbs_list' %}">MySQL</a>
                </li>

                <li class="{{ var8 }}">
                    <strong>添加数据库</strong>
                </li>
            </ol>
        </div>
        <div class="col-lg-2">

        </div>
    </div>

    <div class="row">
        <div class="col-lg-12">
            <div class="ibox float-e-margins">
                <div class="ibox-title">
                    <h5>添加数据库</h5>
                    <div class="ibox-tools">
                        <a class="collapse-link">
                            <i class="fa fa-chevron-up"></i>
                        </a>

                        <a class="close-link">
                            <i class="fa fa-times"></i>
                        </a>
                    </div>
                </div>
                <div class="ibox-content">
                    <form method="post" class="form-horizontal">{% csrf_token %}
                        <div class="form-group">
                            <label class="col-sm-2 control-label">业务组</label>
                                <div class="col-sm-10">
                                    <select class="form-control m-b" id="id_departments" name="departments">
                                        {% for item in departments %}
                                            <option value="{{ item.id }}">{{ item.name }}</option>
                                        {% endfor %}
                                    </select>
                                </div>
                        </div>

                        <div class="hr-line-dashed"></div>

                        <div class="form-group">
                            <label class="col-sm-2 control-label">实例名称</label>
                            <div class="col-sm-10">
                                 <input id="id_schema" name="schema" type="text" class="form-control" value="{{ dbs.schema }}" />
                            </div>
                        </div>

                        <div class="hr-line-dashed"></div>

                        <div class="form-group">
                            <label class="col-sm-2 control-label">实例别名</label>
                            <div class="col-sm-10">
                                 <input id="id_alias_name" name="alias_name" type="text" class="form-control"
                                        value="{{ dbs.alias_name }}" />
                            </div>
                        </div>

                        <div class="hr-line-dashed"></div>

                        <div class="form-group">
                            <label class="col-sm-2 control-label">数据库地址</label>
                            <div class="col-sm-10">
                                 <input id="id_ip_address" name="ip_address" type="text" class="form-control"
                                        value="{{ dbs.ip_address }}" />
                            </div>
                        </div>

                        <div class="hr-line-dashed"></div>

                        <div class="form-group">
                            <label class="col-sm-2 control-label">端口</label>
                            <div class="col-sm-10">
                                 <input id="id_port" name="port" type="text" class="form-control"
                                        value="{{ dbs.port }}" />
                            </div>
                        </div>

                        <div class="hr-line-dashed"></div>

                        <div class="form-group">
                            <label class="col-sm-2 control-label">实例用户</label>
                            <div class="col-sm-10">
                                 <input id="id_schema_user" name="schema_user" type="text" class="form-control"
                                        value="{{ dbs.schema_user }}" />
                            </div>
                        </div>

                        <div class="hr-line-dashed"></div>

                        <div class="form-group">
                            <label class="col-sm-2 control-label">实例用户密码</label>
                            <div class="col-sm-10">
                                 <input id="id_schema_pass" name="schema_pass" type="text" class="form-control"
                                        value="{{ dbs.schema_pass }}" />
                            </div>
                        </div>

                        <div class="hr-line-dashed"></div>

                        <div class="form-group">
                            <label class="col-sm-2 control-label">游戏分区</label>
                                <div class="col-sm-10">
                                    <div class="col-lg-4 m-l-n div_left">
                                        <select class="form-control" multiple="multiple" id="id_zones", name="target_zones">
                                            {% for zone in zones %}
                                                <option value="{{ zone.id }}">{{ zone.name }}</option>
                                            {% endfor %}
                                        </select>
                                    </div>

                                    <div class="col-lg-4 m-l-n div_right">
                                        <select class="form-control" multiple="multiple" id="select_list" name="zones">
                                            {% for zone in dbs.zones.all %}
                                                <option selected value="{{ zone.id }}">{{ zone.name }}</option>
                                            {% endfor %}
                                        </select>
                                    </div>
                                </div>
                        </div>

                        <div class="hr-line-dashed"></div>


                        <div class="form-group">
                            <div class="col-sm-4 col-sm-offset-2">
                                <button class="btn btn-white" type="submit">取消</button>
                                <button class="btn btn-primary" type="submit">保存</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

{% block content2 %}
    <script>
	    $(function(){
		    //点击添加将左边多选选中的添加至右边
			$(".add").click(function(){
			    var get_more = $(".div_left :selected");
				//循环写入右边框中
				get_more.each(function(){
                    $("#select_list").append(this);
				})

			})
			//双击左边框单选添加至右边
	     	$('#id_zones').dblclick(function(){
			    var get_one = $(this).find("option:selected");
				$("#select_list").append(get_one);
			});
			//双击右边框中选项，则删除该项,并复原到左边
			$('#select_list').dblclick(function(){
			    var del_one = $(this).find("option:selected");
				$('#id_zones').append(del_one);
			});
		})
	</script>
{% endblock %}

templates/databases/database_list.html
{% extends 'base.html' %}
{% block content %}
    <div class="row wrapper border-bottom white-bg page-heading">
        <div class="col-lg-10">
            <h2>数据库</h2>
            <ol class="breadcrumb">
                <li>
                    <a href="{% url 'dashboard' %}">Home</a>
                </li>

                <li>
                    <a href="{% url 'dbs_list' %}">MySQL</a>
                </li>

                <li class={{ var8 }}>
                    <strong>数据库</strong>
                </li>
            </ol>
        </div>
        <div class="col-lg-2">
        </div>
    </div>
    <div class="wrapper wrapper-content animated fadeInRight">
        <div class="row">
            <div class="col-lg-12">
                <div class="ibox float-e-margins">
                    <div class="ibox-title">
                        <!--<h5>Basic Data Tables example with responsive plugin</h5>-->
                        <a href="{% url 'dbs_add' %}" class="btn btn-primary">添加实例</a>
                        <div class="ibox-tools">
                            <a class="collapse-link">
                                <i class="fa fa-chevron-up"></i>
                            </a>
                            <a class="close-link">
                                <i class="fa fa-times"></i>
                            </a>
                        </div>
                    </div>
                    <div class="ibox-content">
                        <div class="table-responsive">
                            <table class="table table-striped table-bordered table-hover dataTables-example"
                                   id="db_list" >
                                <thead>
                                <tr>
                                    <!--<th>多选</th>-->
                                    <th>实例名</th>
                                    <th>别名</th>
                                    <th>所属业务组</th>
                                    <th>网络地址</th>
                                    <th>服务端口</th>
                                    <th>游戏分区</th>
                                    <th>操作</th>
                                </tr>
                                </thead>
                                <tbody>
                                    {% for db in dbs %}
                                        <tr class="gradeX">
                                            <td>{{ db.schema}}</td>
                                            <td>{{ db.alias_name }}</td>
                                            <td>{{ db.departments.name}}</td>
                                            <td>{{ db.ip_address }}</td>
                                            <td>{{ db.port }}</td>
                                            <td>{{ db.zones.all|join:","|safe|truncatewords_html:5 }}</td>
                                            <td>
                                                <a class="btn btn-info" href="{% url "dbs_edit" db.id %}">编辑</a>
                                                <a href="javascript:void(0);" deleteId="{{ db.id }}" class="btn btn-danger">删除</a>
                                                <a class="btn btn-primary" href="{% url 'dbs_detail' db.id %}">管理</a></td>
                                        </tr>
                                    {% endfor %}
                                </tbody>
                                <tfoot>
                                <tr>
                                    <th>实例名</th>
                                    <th>别名</th>
                                    <th>所属业务组</th>
                                    <th>网络地址</th>
                                    <th>服务端口</th>
                                    <th>游戏分区</th>
                                    <th>操作</th>
                                </tr>
                                </tfoot>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

templates/databases/dba_add.html
{% extends 'base.html' %}
{% block content %}
    <div class="row wrapper border-bottom white-bg page-heading">
        <div class="col-lg-10">
            <h2>添加帐户</h2>
            <ol class="breadcrumb">
                <li>
                    <a href="{% url 'dashboard' %}">Home</a>
                </li>
                <li>
                    <a href="{% url 'dbs_list' %}">MySQL</a>
                </li>

                <li class="{{ var8 }}">
                    <strong>添加帐户</strong>
                </li>
            </ol>
        </div>
        <div class="col-lg-2">

        </div>
    </div>

    <div class="row">
        <div class="col-lg-12">
            <div class="ibox float-e-margins">
                <div class="ibox-title">
                    <h5>添加数据库</h5>
                    <div class="ibox-tools">
                        <a class="collapse-link">
                            <i class="fa fa-chevron-up"></i>
                        </a>
                        <a class="close-link">
                            <i class="fa fa-times"></i>
                        </a>
                    </div>
                </div>
                <div class="ibox-content">
                    <form method="post" class="form-horizontal">{% csrf_token %}
                        <ul>{% csrf_token %}
                            {{ form.as_p }}
                        </ul>
                        <div class="hr-line-dashed"></div>
                        <div class="form-group">
                            <div class="col-sm-4 col-sm-offset-2">
                                <button class="btn btn-white" type="submit">取消</button>
                                <button class="btn btn-primary" type="submit">保存</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

templates/databases/dba_detail.html
{% extends 'base.html' %}
{% block content %}
    <div class="row wrapper border-bottom white-bg page-heading">
        <div class="col-sm-4">
            <h2>详情</h2>
            <ol class="breadcrumb">
                <li>
                    <a href="{% url 'dashboard' %}">Home</a>
                </li>
                <li class="{{ var8 }}">
                    <strong><a href="{% url 'dbs_list' %}">MySQL</a></strong>
                </li>
                <li class="{{ var8 }}">
                    <strong>详情页</strong>
                </li>
            </ol>
        </div>
    </div>
        <div class="row">
            <div class="col-lg-9">
                <div class="wrapper wrapper-content animated fadeInUp">
                    <div class="ibox">
                        <div class="ibox-content">
                            <div class="row">
                                <div class="col-lg-12">
                                    <div class="m-b-md">
                                        <h2>数据库详情页</h2>
                                    </div>
                                    <dl class="dl-horizontal">
                                        <dt>Status:</dt><dd><span class="label label-primary">可用</span></dd>
                                    </dl>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-lg-5">
                                    <dl class="dl-horizontal">

                                        <dt>业务组:</dt> <dd>{{ db_accounts.databases.departments.name }}</dd>
                                        <dt>分区:</dt> <dd>{{ db_accounts.databases.zones.name }}</dd>
                                        <dt>数据库名:</dt> <dd>{{ db_accounts.databases.db_name }}</dd>
                                        <dt>别名:</dt> <dd>{{ db_accounts.databases.db_alias_name }}</dd>
                                        <dt>主机:</dt> <dd>{{ db_accounts.databases.db_host}}</dd>
                                        <dt>类型:</dt> <dd>{{ db_accounts.databases.db_type }}</dd>
                                        <dt>公司:</dt> <dd><a href="#" class="text-navy"> Leshu Company</a> </dd>
                                        <!--<dt>程序迭代版本:</dt> <dd> 	v1.4.2 </dd>-->
                                    </dl>
                                </div>
                                <div class="col-lg-7" id="cluster_info">
                                    <dl class="dl-horizontal" >

                                        <dt>用户名:</dt> <dd>{{ db_accounts.db_username }}</dd>
                                        <dt>密码:</dt> <dd>{{ db_accounts.db_password }}</dd>
{#                                        <dt>密码:</dt> <dd> 	10.07.2014 23:36:57 </dd>#}
{#                                        <dt>Participants:</dt>#}
{#                                        <dd class="project-people">#}
{#                                        <a href=""><img alt="image" class="img-circle" src="img/a3.jpg"></a>#}
{#                                        <a href=""><img alt="image" class="img-circle" src="img/a1.jpg"></a>#}
{#                                        <a href=""><img alt="image" class="img-circle" src="img/a2.jpg"></a>#}
{#                                        <a href=""><img alt="image" class="img-circle" src="img/a4.jpg"></a>#}
{#                                        <a href=""><img alt="image" class="img-circle" src="img/a5.jpg"></a>#}
{#                                        </dd>#}
                                    </dl>
                                </div>

                                <!--<div class="row">
                                    <div class="col-lg-12">
                                        <dl class="dl-horizontal">
                                            <dt>Completed:</dt>
                                            <dd>
                                                <div class="progress progress-striped active m-b-sm">
                                                    <div style="width: 100%;" class="progress-bar"></div>
                                                </div>
                                                <small>项目组设置完成度<strong>100%</strong></small>
                                            </dd>
                                        </dl>
                                    </div>
                                </div>-->
                            </div>
                        </div>
                    </div>
                </div>
            </div>

        <div class="col-lg-3">
                <div class="wrapper wrapper-content project-manager">
                    <h4>描述</h4>
{#                    <img src="img/zender_logo.png" class="img-responsive">#}
                    <p class="small">
                        Mysql相关设置
                    </p>
                    <p class="small font-bold">
                        <span><i class="fa fa-circle text-warning"></i> High priority</span>
                    </p>
                    <h5>项目标签</h5>
                    <ul class="tag-list" style="padding: 0">
                        <li><a href=""><i class="fa fa-tag"></i> {{ db_accounts.databases.db_type }}</a></li>
                    </ul>
{#                    <h5>Project files</h5>#}
{#                    <ul class="list-unstyled project-files">#}
{#                        <li><a href=""><i class="fa fa-file"></i> Project_document.docx</a></li>#}
{#                        <li><a href=""><i class="fa fa-file-picture-o"></i> Logo_zender_company.jpg</a></li>#}
{#                        <li><a href=""><i class="fa fa-stack-exchange"></i> Email_from_Alex.mln</a></li>#}
{#                        <li><a href=""><i class="fa fa-file"></i> Contract_20_11_2014.docx</a></li>#}
{#                    </ul>#}
{#                    <div class="text-center m-t-md">#}
{#                        <a href="#" class="btn btn-xs btn-primary">Add files</a>#}
{#                        <a href="#" class="btn btn-xs btn-primary">Report contact</a>#}
{##}
{#                    </div>#}
                </div>
            </div>
    </div>

{% endblock %}

templates/databases/dba_list.html
{% extends 'base.html' %}
{% block content %}
    <div class="row wrapper border-bottom white-bg page-heading">
        <div class="col-lg-10">
            <h2>帐号管理</h2>
            <ol class="breadcrumb">
                <li>
                    <a href="{% url 'dashboard' %}">Home</a>
                </li>

                <li>
                    <a href="{% url 'dbs_list' %}">MySQL</a>
                </li>

                <li class={{ var8 }}>
                    <strong>帐号管理</strong>
                </li>
            </ol>
        </div>
        <div class="col-lg-2">
        </div>
    </div>
    <div class="wrapper wrapper-content animated fadeInRight">
        <div class="row">
            <div class="col-lg-12">
                <div class="ibox float-e-margins">
                    <div class="ibox-title">
                        <!--<h5>Basic Data Tables example with responsive plugin</h5>-->
                        <a href="{% url 'dba_add' %}" class="btn btn-primary">创建帐号</a>
                        <div class="ibox-tools">
                            <a class="collapse-link">
                                <i class="fa fa-chevron-up"></i>
                            </a>
                            <a class="close-link">
                                <i class="fa fa-times"></i>
                            </a>
                        </div>
                    </div>
                    <div class="ibox-content">
                        <div class="table-responsive">
                            <table class="table table-striped table-bordered table-hover dataTables-example"
                                   id="mysql_user_list" >
                                <thead>
                                <tr>
                                    <!--<th>多选</th>-->
                                    <th>用户名</th>
                                    <th>主机</th>
                                    <th>创建时间</th>
                                    <th>更新时间</th>
                                    <th>备注</th>
                                    <th>操作</th>
                                </tr>
                                </thead>
                                <tbody>
                                    {% for account in db_accounts %}
                                        <tr class="gradeX">
                                            <td>{{ account.username }}</td>
                                            <td>{{ account.hosts }}</td>
                                            <td>{{ account.create_time | date:'Y-m-d:H:i:s' }}</td>
                                            <td>{{ account.edit_time | date:'Y-m-d:H:i:s' }}</td>
                                            <td>{{ account.content }}</td>
                                            <td>
                                                <a class="btn btn-info" href="{% url "dba_edit" account.id %}">修改权限</a>
                                                <a href="javascript:void(0);" deleteId="{{ account.id }}" class="btn btn-danger">删除帐号</a>
                                                <div class="btn-group">
                                                    <button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown">更多<span class="caret"></span></button>
                                                    <ul class="dropdown-menu" role="menu">
                                                        <li><a href="#">重置密码</a></li>
                                                        <li><a href="#">删除帐号</a></li>
                                                        <li><a href="#">修改备注</a></li>
                                                    </ul>
                                                </div>
{#                                                <a class="btn btn-primary" href="{% url 'dba_detail' account.id %}">详情</a></td>#}
                                        </tr>
                                    {% endfor %}
                                </tbody>
                                <tfoot>
                                <tr>
                                    <!--<th>多选</th>-->
                                    <th>用户名</th>
                                    <th>主机</th>
                                    <th>创建时间</th>
                                    <th>更新时间</th>
                                    <th>备注</th>
                                    <th>操作</th>
                                </tr>
                                </tfoot>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock %}