OMS/urls.py
from django.conf.urls import patterns, include, url
from django.conf import settings


urlpatterns = patterns('',
                       url(r'accounts/', include('accounts.urls')),
                       url(r'dashboard/', include('dashboard.urls')),
                       url(r'departments/', include('departments.urls')),
                       url(r'oms_config/', include('oms_config.urls')),
                       url(r'dbs_mysql/', include('dbs_mysql.urls')),
                       url(r'dbs_redis/', include('dbs_redis.urls')),
                       url(r'repository/', include('repository.urls')),
                       url(r'assets/', include('assets.urls')),
                       url(r'saltstack/', include('saltstack.urls')),
                       url(r'^media/(?P<path>.*)$', 'django.views.static.serve',
                           {'document_root': settings.MEDIA_ROOT}),
                       )

oms_config/urls.py
# from django.conf.urls import url
from django.conf.urls import patterns, url
from oms_config import zone_views, info_views, upload_views, path_views, produce_views
from oms_config import domain_views


urlpatterns = patterns('',
                       # zone_info
                       url(r'^produce_add', produce_views.produce_add, name='produce_add'),
                       url(r'^produce_edit/(?P<pk>\d+)$', produce_views.produce_edit, name='produce_edit'),
                       url(r'^produce_del/', produce_views.produce_del, name='produce_del'),
                       url(r'^produce_list/', produce_views.produce_list, name='produce_list'),
                       url(r'^produce_detail/(?P<pk>\d+)$', produce_views.produce_detail, name='produce_detail'),
                       # file_upload
                       url(r'^upload_list/', upload_views.upload_file_list, name='upload_list'),
                       url(r'^upload_file/', upload_views.file_upload, name='upload_file'),
                       url(r'^upload_del/', upload_views.upload_del, name='upload_del'),
                       url(r'^multi_file_upload/', upload_views.multi_file_upload, name='multi_file_upload'),
                       url(r'^upload_action/', upload_views.upload_action, name='upload_action'),
                       url(r'^show_files/(?P<pk>\d+)$', upload_views.show_files, name='show_files'),
                       # game_zone
                       url(r'^game_zone_list/$', zone_views.game_zone_list, name='game_zone_list'),
                       url(r'^game_zone_add/$', zone_views.game_zone_add, name='game_zone_add'),
                       url(r'^game_zone_edit/(?P<pk>\d+)$', zone_views.game_zone_edit, name='game_zone_edit'),
                       url(r'^game_zone_del/', zone_views.game_zone_del, name='game_zone_del'),
                       url(r'^game_zone_detail/(?P<pk>\d+)$', zone_views.game_zone_detail, name='game_zone_detail'),
                       # info
                       url(r'^info_add', info_views.info_add, name='info_add'),
                       url(r'^info_edit/(?P<pk>\d+)$', info_views.info_edit, name='info_edit'),
                       url(r'^info_del/', info_views.info_del, name='info_del'),
                       url(r'^info_list/', info_views.info_list, name='info_list'),
                       url(r'^info_detail/(?P<pk>\d+)$', info_views.info_detail, name='info_detail'),
                       url(r'^game_zone_copy/', info_views.game_zone_copy, name='game_zone_copy'),
                       url(r'^get_zones/(?P<pk>\d+)$', info_views.get_zones, name='get_zones'),
                       # domain
                       url(r'^domain_add/', domain_views.domain_add, name='domain_add'),
                       url(r'^domain_del/', domain_views.domain_del, name='domain_del'),
                       url(r'^domain_edit/(?P<pk>\d+)$', domain_views.domain_edit, name='domain_edit'),
                       url(r'^domain_list/', domain_views.domain_list, name='domain_list'),
                       url(r'^domain_detail/(?P<pk>\d+)$', domain_views.domain_detail, name='domain_detail'),
                       # path
                       url(r'^path_add/', path_views.path_add, name='path_add'),
                       url(r'^path_del/', path_views.path_del, name='path_del'),
                       url(r'^path_edit/(?P<pk>\d+)$', path_views.path_edit, name='path_edit'),
                       url(r'^path_list/', path_views.path_list, name='path_list'),
                       url(r'^path_detail/(?P<pk>\d+)', path_views.path_detail, name='path_detail'),
                       )

assets/models.py
# --*-- coding: utf-8 --*--

from django.db import models
from departments.models import Department
from oms_config.models import Zone

# Create your models here.


class Hardware(models.Model):
    UNIT_CHOICES = (
        (u'1', u'GB'),
        (u'2', u'Core'),
    )

    name = models.CharField(max_length=20, blank=True, null=True, verbose_name=u'硬件名')
    value = models.IntegerField(blank=True, null=True, verbose_name=u'硬件值')
    unit = models.CharField(max_length=10, blank=True, null=True, choices=UNIT_CHOICES, verbose_name=u'单位')

    class Meta:
        permissions = (
            ('view_hardware', 'Can view Hardware'),
        )

    def __unicode__(self):
        return '%s %s %s' % (self.name, self.value, self.get_unit_display())


class Network(models.Model):
    NET_TYPE_CHOICES = (
        (u'1', u'BGP'),
        (u'2', u'电信'),
        (u'3', u'联通'),
        (u'4', u'移动'),
        (u'5', u'教育'),
        (u'6', u'内网'),
    )

    UNIT_CHOICES = (
        (u'1', u'Mbps'),
    )

    public_address = models.IPAddressField(blank=True, null=True, verbose_name=u'公网地址')
    private_address = models.IPAddressField(blank=True, null=True, verbose_name=u'内网地址')
    bandwidth = models.IntegerField(blank=True, null=True, verbose_name=u'带宽')
    provide = models.CharField(max_length=20, verbose_name=u'接入商', blank=True, null=True)
    net_type = models.CharField(max_length=20, blank=True, null=True, verbose_name=u'网络类型', choices=NET_TYPE_CHOICES)
    unit = models.CharField(max_length=10, blank=True, null=True, verbose_name=u'单位', choices=UNIT_CHOICES)
    bind = models.BooleanField(default=False, verbose_name=u'绑定', blank=True)

    class Meta:
        permissions = (
            ('view_network', 'Can view network'),
        )

    def __unicode__(self):
        return '%s %s %s %s %s %s' % (self.public_address, self.private_address, self.provide,
                                      self.net_type, self.bandwidth, self.get_unit_display())


class Services(models.Model):
    name = models.CharField(max_length=50, verbose_name=u'服务名')
    port = models.IntegerField(verbose_name=u'端口', blank=True, null=True)

    class Meta:
        permissions = (
            ('view_service', 'can view services'),
        )

    def __unicode__(self):
        return self.name


class Tag(models.Model):
    name = models.CharField(max_length=20, verbose_name=u'标签名', blank=True, null=True, unique=True)

    class Meta:
        permissions = (
            ('view_tag', 'Can view tags'),
        )

    def __unicode__(self):
        return self.name


class Assets(models.Model):
    HOST_TYPE_CHOICES = (
        (u'1', u'物理机'),
        (u'2', u'云主机'),
        (u'3', u'虚拟机'),
    )

    OS_CHOICES = (
        (u'1', u'CentOS 7.2 X86 64bit'),
        (u'2', u'CentOS 7.0 x86 64bit'),
        (u'3', u'CentOS 6.5 x86 64bit'),
    )

    host_name = models.CharField(max_length=50, verbose_name=u'主机名', unique=True)
    alias_name = models.CharField(max_length=100, verbose_name=u'可见名', blank=True, null=True)
    host_type = models.CharField(max_length=10, blank=True, null=True,
                                 choices=HOST_TYPE_CHOICES, verbose_name=u'主机类型')
    tag = models.ManyToManyField(Tag, verbose_name=u'标识')
    game_zone = models.ManyToManyField(Zone, verbose_name=u'游戏区')
    os = models.CharField(max_length=10, blank=True, null=True,
                          choices=OS_CHOICES, verbose_name=u'操作系统')
    superuser = models.CharField(max_length=20, verbose_name=u'管理员', default=u'root')
    superuser_pass = models.CharField(max_length=50, verbose_name=u'管理员密码', blank=True, null=True)
    is_online = models.BooleanField(blank=True, default=False, verbose_name=u'在线')
    is_unused = models.BooleanField(verbose_name=u'闲置', default=False)
    is_master = models.BooleanField(blank=True, default=False, verbose_name=u'salt-master')
    is_minion = models.BooleanField(blank=True, default=False, verbose_name=u'salt-minion')
    hardware = models.ManyToManyField(Hardware, verbose_name=u'硬件配置')
    networks = models.OneToOneField(Network, on_delete=models.CASCADE, verbose_name=u'网络', related_name='assets')
    departments = models.ForeignKey(Department, on_delete=models.CASCADE, verbose_name=u'业务组', blank=True, null=True)
    services = models.ManyToManyField(Services, verbose_name=u'运行的服务')

    class Meta:
        permissions = (
            ('view_assets', 'Can view assets'),
        )

    def __unicode__(self):
        return self.alias_name


class SysUser(models.Model):
    servers = models.ForeignKey(Assets, verbose_name=u'服务器')
    sys_user = models.CharField(max_length=50, verbose_name=u'用户', blank=True, null=True)
    sys_pass = models.CharField(max_length=200, verbose_name=u'密码', blank=True, null=True)

    class Meta:
        permissions = (
            ('view_sysuser', 'can view sys user information'),
        )

    def __unicode__(self):
        return '%s %s' % (self.sys_user, self.sys_pass)

oms_config/models.py
# -*- coding:utf8 -*-

from django.db import models
from departments.models import Department


# Create your models here.


class Zone(models.Model):
    departments = models.ForeignKey(Department, on_delete=models.CASCADE, verbose_name=u'业务组')
    name = models.CharField(max_length=50, verbose_name=u'游戏分区', unique=True)
    content = models.CharField(max_length=200, verbose_name=u'备注', blank=True, null=True)

    class Meta:
        permissions = (
            ('view_zone', 'Can view game zone'),
        )

    def __unicode__(self):
        return self.name


class Information(models.Model):
    zones = models.ForeignKey(Zone, on_delete=models.CASCADE,
                              verbose_name=u'游戏分区', blank=True, null=True)
    key = models.CharField(max_length=50, verbose_name=u'字段名')
    value = models.CharField(max_length=200, verbose_name=u'字段值')
    timestamp = models.DateTimeField(auto_now=True, blank=True, null=True)
    context = models.CharField(max_length=200, verbose_name=u'备注', blank=True, null=True)

    class Meta:
        ordering = ['-timestamp']
        permissions = (
            ('view_information', 'Can view information'),
        )

    def __unicode__(self):
        return '%s %s' % (self.name, self.value)


class Upload(models.Model):
    departments = models.ForeignKey(Department, verbose_name=u'业务组', on_delete=models.CASCADE)
    title = models.CharField(max_length=50, verbose_name=u'标题')
    doc_file = models.FileField(upload_to='Upload')
    timestamp = models.DateTimeField(verbose_name=u'上传时间', auto_now=True)

    class Meta:
        ordering = ['-timestamp']
        permissions = (
            ('view_upload', 'can view upload file'),
        )

    def __unicode__(self):
        return '%s' % self.doc_file

    def display_text_file(self):
        with open(self.doc_file.path) as fp:
            return fp.read()


class Path(models.Model):
    departments = models.ForeignKey(Department, on_delete=models.CASCADE, verbose_name=u'业务组')
    path_key = models.CharField(max_length=100, verbose_name=u'路径名', unique=True)
    path_value = models.CharField(max_length=2000, verbose_name=u'路径值')
    timestamp = models.DateTimeField(verbose_name=u'时间', auto_now=True)

    class Meta:
        permissions = (
            ('view_path', 'can view path'),
        )

    def __unicode__(self):
        return self.path_value


class Produce(models.Model):
    departments = models.ForeignKey(Department, verbose_name=u'业务组', on_delete=models.CASCADE)
    zones = models.ManyToManyField(Zone, verbose_name=u"游戏分区")
    config_file = models.CharField(max_length=200, verbose_name=u'配置文件')
    generate_path = models.CharField(max_length=200, verbose_name=u'生成路径')
    project_name = models.CharField(max_length=50, verbose_name=u'对应仓库项目')
    create_time = models.DateTimeField(verbose_name=u'生成时间', auto_now=True)

    class Meta:
        ordering = ['-create_time']
        permissions = (
            ('view_produce', 'Can view produce'),
        )

    def __unicode__(self):
        return self.generate_path


class Domain(models.Model):
    departments = models.ForeignKey(Department, verbose_name=u'业务组', on_delete=models.CASCADE)
    zones = models.ForeignKey(Zone, verbose_name=u'游戏分区', on_delete=models.CASCADE)
    name = models.CharField(max_length=200, verbose_name=u'域名')
    timestamp = models.DateField(verbose_name=u'时间', auto_now=True)

    class Meta:
        ordering = ['-timestamp']
        permissions = (
            ('view_domain', 'Can view Domain'),
        )

    def __unicode__(self):
        return '%s | %s' % (self.zones, self.name)

oms_config/forms.py
# --*-- coding:utf8 --*--

from django import forms
from models import Zone, Information, Upload, Path, Produce, Domain
from repository.models import Repository


class ZoneForm(forms.ModelForm):

    class Meta:
        model = Zone
        fields = '__all__'


class ZoneEditForm(forms.ModelForm):

    class Meta:
        model = Zone
        fields = '__all__'


class InformationForm(forms.ModelForm):

    class Meta:
        model = Information
        fields = '__all__'


class UploadForm(forms.ModelForm):

    class Meta:
        model = Upload
        fields = '__all__'


class PathForm(forms.ModelForm):

    class Meta:
        model = Path
        fields = '__all__'


class ProduceForm(forms.ModelForm):
    zones = forms.ModelMultipleChoiceField(label=u'选择分区', widget=forms.CheckboxSelectMultiple(),
                                           queryset=Zone.objects.all())
    config_file = forms.ModelChoiceField(label=u'模板文件', queryset=Upload.objects.all())
    generate_path = forms.ModelChoiceField(label=u'生成文件', queryset=Path.objects.filter(path_key__contains=u'配置生成目录'))
    project_name = forms.ModelChoiceField(label=u'对应仓库项目', queryset=Repository.objects.all())

    class Meta:
        model = Produce
        fields = '__all__'


class DomainForm(forms.ModelForm):

    class Meta:
        model = Domain
        fields = '__all__'

templates/oms_config/domain_add.html
{% extends 'base.html' %}
{% block content %}
    <div class="row wrapper border-bottom white-bg page-heading">
        <div class="col-lg-10">
            <h2>添加域名</h2>
            <ol class="breadcrumb">
                <li>
                    <a href="{% url 'dashboard' %}">Home</a>
                </li>
                <li>
                    <a href="#">系统设置</a>
                </li>
                <li class="{{ var4 }}">
                    <strong>添加域名</strong>
                </li>
            </ol>
        </div>
        <div class="col-lg-2">

        </div>
    </div>

    <div class="row">
        <div class="col-lg-12">
            <div class="ibox float-e-margins">
                <div class="ibox-title">
                    <h5>添加域名</h5>
                    <div class="ibox-tools">
                        <a class="collapse-link">
                            <i class="fa fa-chevron-up"></i>
                        </a>
                        <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                            <i class="fa fa-wrench"></i>
                        </a>
                        <ul class="dropdown-menu dropdown-user">
                            <li><a href="#">Config option 1</a>
                            </li>
                            <li><a href="#">Config option 2</a>
                            </li>
                        </ul>
                        <a class="close-link">
                            <i class="fa fa-times"></i>
                        </a>
                    </div>
                </div>
                <div class="ibox-content">
                    <form method="post" class="form-horizontal">{% csrf_token %}
                        <div class="form-group">
                            <label class="col-sm-2 control-label">业务组</label>
                                <div class="col-sm-10">
                                        <select class="form-control m-b" id="id_departments" name="departments">
                                            {% for item in departments %}
                                            <option value="{{ item.id }}">{{ item.name }}</option>
                                            {% endfor %}
                                        </select>
                                </div>
                        </div>

                        <div class="form-group">
                            <label class="col-sm-2 control-label">游戏分区</label>
                            <div class="col-sm-10">
                                 <select class="form-control m-b" id="id_zones" name="zones">
                                     {% for zone in zones %}
                                     <option value="{{ zone.id }}">{{ zone.name }}</option>
                                     {% endfor %}
                                 </select>
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="col-sm-2 control-label">域名</label>
                            <div class="col-sm-10">
                                    <input id="id_name" name="name" type="text" class="form-control"
                                           value="{{ domain_object.name }}">
                            </div>
                        </div>

                        <div class="hr-line-dashed"></div>

                        <div class="form-group">
                            <div class="col-sm-4 col-sm-offset-2">
                                <button class="btn btn-white" type="submit">取消</button>
                                <button class="btn btn-primary" type="submit">保存</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

templates/oms_config/information_add.html
{% extends 'base.html' %}
{% block content %}
    <div class="row wrapper border-bottom white-bg page-heading">
        <div class="col-lg-10">
            <h2>添加键值</h2>
            <ol class="breadcrumb">
                <li>
                    <a href="{% url 'dashboard' %}">Home</a>
                </li>
                <li>
                    <a href="{% url 'game_zone_list' %}">系统设置</a>
                </li>

                <li class="{{ var4 }}">
                    <strong>添加键值</strong>
                </li>
            </ol>
        </div>
        <div class="col-lg-2">

        </div>
    </div>

    <div class="row">
        <div class="col-lg-12">
            <div class="ibox float-e-margins">
                <div class="ibox-title">
                    <h5>添加键值</h5>
                    <div class="ibox-tools">
                        <a class="collapse-link">
                            <i class="fa fa-chevron-up"></i>
                        </a>
                        <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                            <i class="fa fa-wrench"></i>
                        </a>
                        <ul class="dropdown-menu dropdown-user">
                            <li><a href="#">Config option 1</a>
                            </li>
                            <li><a href="#">Config option 2</a>
                            </li>
                        </ul>
                        <a class="close-link">
                            <i class="fa fa-times"></i>
                        </a>
                    </div>
                </div>
                <div class="ibox-content">
                    <form method="post" class="form-horizontal">{% csrf_token %}
                        <div class="form-group">
                            <label class="col-sm-2 control-label">游戏分区</label>

                                <div class="col-sm-10">
                                        <select class="form-control m-b" id="id_zones" name="zones">
                                            <option value="">--------------请选择--------------</option>
                                            {% for item in zones %}
                                                {% ifequal select.id item.id %}
                                                    <option value="{{ item.id }}" selected>{{ item.name }}</option>
                                                {% else %}
                                                    <option value="{{ item.id }}">{{ item.name }}</option>
                                                {% endifequal %}
                                            {% endfor %}
                                        </select>
                                </div>
                        </div>

                        <div class="form-group">
                            <label class="col-sm-2 control-label">字段名</label>
                            <div class="col-sm-10">
                                    <input id="id_key" name="key" type="text" class="form-control" value="{{ info.key }}">
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="col-sm-2 control-label">字段值</label>
                            <div class="col-sm-10">
                                    <input id="id_value" name="value" type="text" class="form-control" value="{{ info.value }}">
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="col-sm-2 control-label">备注</label>
                            <div class="col-sm-10">
                                <label>
                                    <input id="id_context" name="context" type="text" class="form-control" value="{{ info.context }}">
                                </label>
                            </div>
                        </div>

                        <div class="hr-line-dashed"></div>

                        <div class="form-group">
                            <div class="col-sm-4 col-sm-offset-2">
                                <button class="btn btn-white" type="submit">取消</button>
                                <button class="btn btn-primary" type="submit">保存</button>
                            </div>
                        </div>

                    </form>

                </div>
            </div>
        </div>
    </div>


{% endblock %}

templates/oms_config/produce_add.html
{% extends 'base.html' %}
{% block content %}
    <div class="row wrapper border-bottom white-bg page-heading">
        <div class="col-lg-10">
            <h2>生成文件</h2>
            <ol class="breadcrumb">
                <li>
                    <a href="{% url 'dashboard' %}">Home</a>
                </li>
                <li>
                    <a href="#">系统设置</a>
                </li>
                <li class="{{ var4 }}">
                    <strong>生成文件</strong>
                </li>
            </ol>
        </div>
        <div class="col-lg-2">

        </div>
    </div>

    <div class="row">
        <div class="col-lg-12">
            <div class="ibox float-e-margins">
                <div class="ibox-title">
                    <h5>生成文件</h5>
                    <div class="ibox-tools">
                        <a class="collapse-link">
                            <i class="fa fa-chevron-up"></i>
                        </a>
                        <a class="close-link">
                            <i class="fa fa-times"></i>
                        </a>
                    </div>
                </div>
                <div class="ibox-content">
                    <form method="post" class="form-horizontal">{% csrf_token %}
                        <div class="form-group">
                            <label class="col-sm-2 control-label">业务组</label>
                                <div class="col-sm-10">
                                    <select class="form-control m-b" id="id_departments" name="departments">
                                        {% for item in departments %}
                                            <option value="{{ item.id }}">{{ item.name }}</option>
                                        {% endfor %}
                                    </select>
                                </div>
                        </div>

                        <div class="hr-line-dashed"></div>

                        <div class="form-group">
                            <label class="col-sm-2 control-label">选择分区</label>

                            <div class="col-sm-10 merge_zones">
                                {% for zone in zones %}
                                <label class="checkbox-inline i-checks">
                                    <input type="checkbox" value="{{ zone.id }}"
                                           id="id_zones_{{ zone.id }}" name="zones"> {{ zone.name }}
                                </label>
                                {% endfor %}
                            </div>
                        </div>

                        <div class="hr-line-dashed"></div>

                        <div class="form-group">
                            <label class="col-sm-2 control-label">模板文件</label>
                                <div class="col-sm-10">
                                    <select class="form-control m-b" id="id_config_file" name="config_file">
                                        {% for item in config_files %}
                                            <option value="{{ item.id }}">{{ item.doc_file }}</option>
                                        {% endfor %}
                                    </select>
                                </div>
                        </div>

                        <div class="hr-line-dashed"></div>

                        <div class="form-group">
                            <label class="col-sm-2 control-label">生成至</label>
                                <div class="col-sm-10">
                                    <select class="form-control m-b" id="id_generate_path" name="generate_path">
                                        {% for item in generate_object %}
                                            <option value="{{ item.id }}">{{ item.path_value }}</option>
                                        {% endfor %}
                                    </select>
                                </div>
                        </div>

                        <div class="hr-line-dashed"></div>

                        <div class="form-group">
                            <label class="col-sm-2 control-label">选择对应仓库</label>
                                <div class="col-sm-10">
                                    <select class="form-control m-b" id="id_project_name" name="project_name">
                                        {% for item in repo_object %}
                                            <option value="{{ item.id }}">{{ item.repo_name }}</option>
                                        {% endfor %}
                                    </select>
                                </div>
                        </div>

                         <div class="hr-line-dashed"></div>


                        <div class="form-group">
                            <div class="col-sm-4 col-sm-offset-2">
                                <button class="btn btn-white" type="submit">取消</button>
                                <button class="btn btn-primary" type="submit">提交</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/oms_config/show_files.html
{% extends 'base.html' %}
{% block content %}
    <div class="row wrapper border-bottom white-bg page-heading">
        <div class="col-lg-10">
            <h2>查看文件</h2>
            <ol class="breadcrumb">
                <li>
                    <a href="{% url 'dashboard' %}">Home</a>
                </li>
                <li>
                    <a href="{% url 'upload_list' %}">查看文件</a>
                </li>
                <li class="active">
                    <strong>查看文件</strong>
                </li>
            </ol>
        </div>
        <div class="col-lg-2">

        </div>
    </div>

    <div class="wrapper wrapper-content animated fadeIn">
        <div class="col-lg-12">
            <div class="ibox float-e-margins">
                <div class="ibox-title">
                    <h5>查看文件</h5>
                    <div class="ibox-tools">
                        <a class="collapse-link">
                            <i class="fa fa-chevron-up"></i>
                        </a>
                        <a class="close-link">
                            <i class="fa fa-times"></i>
                        </a>
                    </div>
                </div>


                <div class="ibox-content">
                    <form method="post" class="form-horizontal">{% csrf_token %}
                        <div class="form-group">
                            <label class="col-sm-2 control-label">业务组</label>
                                <div class="col-sm-10">
                                    <input id="id_departments", name="departments", type="text" class="form-control"
                                    value="{{ doc_department }}">
                                </div>
                        </div>

                        <div class="hr-line-dashed"></div>

                        <div class="form-group">
                            <label class="col-sm-2 control-label">标题</label>
                            <div class="col-sm-10">
                                    <input id="id_title" name="title" type="text" class="form-control" value="{{ doc_title }}">
                            </div>
                        </div>

                        <div class="hr-line-dashed"></div>

                        <div class="form-group">
                            <label class="col-sm-2 control-label">文件内容</label>
                            <div class="col-sm-10">
                                <textarea class="form-control" rows="10" id="code1">{{ doc_content }}
                                </textarea>
                            </div>
                        </div>

                        <div class="hr-line-dashed"></div>

                        <div class="form-group">
                            <div class="col-sm-4 col-sm-offset-2">
                                <button class="btn btn-white" type="submit">取消</button>
                                <button class="btn btn-primary" type="submit">保存</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

{% block content2 %}
    <script src="/static/js/views_code.js"></script>
{% endblock %}